# .rubocop.yml

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80 # Ajuste conforme necessário

Style/Documentation:
  Enabled: true # Adicione o departamento apropriado se necessário

Style/AsciiComments:
  Enabled: true # Adicione o departamento apropriado se necessário

Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
