# .rubocop.yml

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80 # Ajuste conforme necessário

Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: true
Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
